# Generated by Django 3.2.3 on 2021-05-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depositos',
            new_name='Deposito',
        ),
    ]
