# Generated by Django 3.2.3 on 2021-05-29 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_depositos_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='tipo_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banco_tipo', to='usuarios.tipobanco'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='tipo_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_tipo', to='usuarios.tipocuenta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comuna_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_comuna', to='usuarios.comunasusuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tipo', to='usuarios.tipousuario'),
        ),
    ]
