# Generated by Django 3.2.3 on 2021-05-24 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacionamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vehiculo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.estacionamiento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='patente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.vehiculo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.tipoestacionamiento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reserva', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='categoria_estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.categoriaestacionamiento'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='comuna_estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.comunaestacionamiento'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='tipo_estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.tipoestacionamiento'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_estacionamiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
