# Generated by Django 3.2.3 on 2021-05-29 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estacionamientos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquedisponibilidad',
            name='numero_bloque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='estado_estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.estadoestacionamiento'),
        ),
        migrations.AlterField(
            model_name='bloquedisponibilidad',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ImagenesEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('estacionamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponibilidad', models.DateField(null=True)),
                ('estacionamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.IntegerField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.reserva')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bloquedisponibilidad',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.disponibilidad'),
        ),
    ]
