# Generated by Django 3.2.3 on 2021-05-29 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210529_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estacionamientos', '0003_auto_20210529_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=25, null=True, verbose_name='N° documento')),
                ('numero_cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.boleta')),
                ('tipo_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_tipo_banco', to='usuarios.tipobanco')),
                ('tipo_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_tipo_cuenta', to='usuarios.tipocuenta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pago', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
