# Generated by Django 3.2.3 on 2021-06-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0004_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloquedisponibilidad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='bloquedisponibilidad',
            name='numero_bloque',
        ),
        migrations.AddField(
            model_name='bloquedisponibilidad',
            name='bloque_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloque_inicio_disponibilidad', to='estacionamientos.bloque'),
        ),
        migrations.AddField(
            model_name='bloquedisponibilidad',
            name='bloque_termino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloque_termino_disponibilidad', to='estacionamientos.bloque'),
        ),
    ]
