# Generated by Django 3.2.3 on 2021-06-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0006_alter_bloquedisponibilidad_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesestacionamiento',
            name='image',
        ),
    ]
