# Generated by Django 3.2.3 on 2021-07-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0007_remove_imagenesestacionamiento_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='precio_bloque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='precio_base',
            field=models.IntegerField(default=0),
        ),
    ]
